version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t docker-cron:latest .
      - docker tag docker-cron:latest 303814004728.dkr.ecr.eu-central-1.amazonaws.com/docker-cron:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 303814004728.dkr.ecr.eu-central-1.amazonaws.com/docker-cron:latest